version: '3.8'

services:
  vscode-extension-env:
    build: .
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
    environment:
      - SHELL=/bin/bash
    command: /bin/bash -c "source ~/.bashrc && conda activate pyenv && /bin/bash"
