/* eslint-disable @typescript-eslint/naming-convention */
export const colorTokens: { [key: string]: string } = {
  colorNeutralStroke1: "#E1E1E1",
  colorBrandForeground2: "#0078D4",
  colorNeutralStroke2: "#525252",
  colorBrandForeground1: "#2899f5",
  colorNeutralBackground3: "#141414",
  colorBrandForeground2Pressed: "#333357",
  DarkAccent: "#FFFFFF",
  LightAccent: "#000000",
  colorNeutralStroke3: "#000000",
  colorNeutralForeground3: "#FFFFFF",
  colorNeutralForeground1: "#000000",
  colorNeutralForeground2: "#333333",
  colorNeutralBackground1: "#FFFFFF",
  colorNeutralBackground2: "#F3F2F1",
  colorNeutralBackground4: "#E1DFDD",
  colorNeutralStroke1Pressed: "#333357",
  colorNeutralStroke2Hover: "#525252",
  colorNeutralStroke3Hover: "#000000",
  colorNeutralForeground1Hover: "#000000",
  colorNeutralForeground2Hover: "#333333",
  colorNeutralBackground1Hover: "#FFFFFF",
  colorPaletteGreenForeground1: "#107C10",
  colorNeutralForeground1Pressed: "#1A1A1A",
  colorNeutralForeground1Selected: "#0F0F0F",
  colorNeutralForeground2Pressed: "#262626",
  colorNeutralForeground2Selected: "#1F1F1F",
  colorNeutralForeground2BrandHover: "#0078D4",
  colorNeutralForeground2BrandPressed: "#005A9E",
  colorNeutralForeground2BrandSelected: "#004578",
  colorNeutralForeground3Hover: "#333333",
  colorNeutralForeground3Pressed: "#4D4D4D",
  colorNeutralForeground3Selected: "#666666",
  colorNeutralForeground3BrandHover: "#0078D4",
  colorNeutralForeground3BrandPressed: "#005A9E",
  colorNeutralForeground3BrandSelected: "#004578",
  colorNeutralForeground4: "#737373",
  colorNeutralForegroundDisabled: "#C8C8C8",
  colorNeutralForegroundInvertedDisabled: "#D9D9D9",
  colorBrandForegroundLink: "#0078D4",
  colorBrandForegroundLinkHover: "#005A9E",
  colorBrandForegroundLinkPressed: "#004578",
  colorBrandForegroundLinkSelected: "#002847",
  colorNeutralForeground2Link: "#0078D4",
  colorNeutralForeground2LinkHover: "#005A9E",
  colorNeutralForeground2LinkPressed: "#004578",
  colorNeutralForeground2LinkSelected: "#002847",
  colorCompoundBrandForeground1: "#0078D4",
  colorCompoundBrandForeground1Hover: "#005A9E",
  colorCompoundBrandForeground1Pressed: "#004578",
  colorNeutralForeground1Static: "#FFFFFF",
  colorNeutralForegroundInverted: "#FFFFFF",
  colorNeutralForegroundInvertedHover: "#E1E1E1",
  colorNeutralForegroundInvertedPressed: "#C8C8C8",
  colorNeutralForegroundInvertedSelected: "#A6A6A6",
  colorNeutralForegroundInverted2: "#F3F2F1",
  colorNeutralForegroundOnBrand: "#FFFFFF",
  colorNeutralForegroundStaticInverted: "#FFFFFF",
  colorNeutralForegroundInvertedLink: "#FFFFFF",
  colorNeutralForegroundInvertedLinkHover: "#E1E1E1",
  colorNeutralForegroundInvertedLinkPressed: "#C8C8C8",
  colorNeutralForegroundInvertedLinkSelected: "#A6A6A6",
  colorBrandForegroundInverted: "#FFFFFF",
  colorBrandForegroundInvertedHover: "#E1E1E1",
  colorBrandForegroundInvertedPressed: "#C8C8C8",
  colorBrandForegroundOnLight: "#004578",
  colorBrandForegroundOnLightHover: "#005A9E",
  colorBrandForegroundOnLightPressed: "#0078D4",
  colorBrandForegroundOnLightSelected: "#2899f5",
  colorNeutralBackground1Pressed: "#F3F2F1",
  colorNeutralBackground1Selected: "#E1E1E1",
  colorNeutralBackground2Pressed: "#C8C8C8",
  colorNeutralBackground2Selected: "#BEBEBE",
  colorNeutralBackground3Hover: "#A6A6A6",
  colorNeutralBackground3Pressed: "#8C8C8C",
  colorNeutralBackground3Selected: "#737373",
  colorNeutralBackground4Hover: "#666666",
  colorNeutralBackground4Pressed: "#4D4D4D",
  colorNeutralBackground4Selected: "#333333",
  colorNeutralBackground5: "#1A1A1A",
  colorNeutralBackground5Hover: "#000000",
  colorNeutralBackground5Pressed: "#1A1A1A",
  colorNeutralBackground5Selected: "#333333",
  colorNeutralBackground6: "#4D4D4D",
  colorNeutralBackgroundInverted: "#FFFFFF",
  colorNeutralBackgroundStatic: "#F3F2F1",
  colorNeutralBackgroundAlpha: "#E1E1E1",
  colorNeutralBackgroundAlpha2: "#C8C8C8",
  colorSubtleBackground: "#F3F2F1",
  colorSubtleBackgroundHover: "#E1E1E1",
  colorSubtleBackgroundPressed: "#C8C8C8",
  colorSubtleBackgroundSelected: "#BEBEBE",
  colorSubtleBackgroundLightAlphaHover: "#A6A6A6",
  colorSubtleBackgroundLightAlphaPressed: "#8C8C8C",
  colorSubtleBackgroundLightAlphaSelected: "#737373",
  colorSubtleBackgroundInverted: "#FFFFFF",
  colorSubtleBackgroundInvertedHover: "#E1E1E1",
  colorSubtleBackgroundInvertedPressed: "#C8C8C8",
  colorSubtleBackgroundInvertedSelected: "#A6A6A6",
  colorTransparentBackground: "#00000000",
  colorTransparentBackgroundHover: "#F3F2F1",
  colorTransparentBackgroundPressed: "#E1E1E1",
  colorTransparentBackgroundSelected: "#C8C8C8",
  colorNeutralBackgroundDisabled: "#F3F2F1",
  colorNeutralBackgroundInvertedDisabled: "#D9D9D9",
  colorNeutralStencil1: "#E1E1E1",
  colorNeutralStencil2: "#C8C8C8",
  colorNeutralStencil1Alpha: "#A6A6A6",
  colorNeutralStencil2Alpha: "#737373",
  colorBackgroundOverlay: "#00000099",
  colorScrollbarOverlay: "#A6A6A6",
  colorBrandBackground: "#004578",
  colorBrandBackgroundHover: "#005A9E",
  colorBrandBackgroundPressed: "#0078D4",
  colorBrandBackgroundSelected: "#2899f5",
  colorCompoundBrandBackground: "#004578",
  colorCompoundBrandBackgroundHover: "#005A9E",
  colorCompoundBrandBackgroundPressed: "#0078D4",
  colorBrandBackgroundStatic: "#004578",
  colorBrandBackground2: "#005A9E",
  colorBrandBackground2Hover: "#0078D4",
  colorBrandBackground2Pressed: "#2899f5",
  colorBrandBackground3Static: "#004578",
  colorBrandBackground4Static: "#002847",
  colorBrandBackgroundInverted: "#FFFFFF",
  colorBrandBackgroundInvertedHover: "#E1E1E1",
  colorBrandBackgroundInvertedPressed: "#C8C8C8",
  colorBrandBackgroundInvertedSelected: "#A6A6A6",
  colorNeutralCardBackground: "#F3F2F1",
  colorNeutralCardBackgroundHover: "#E1E1E1",
  colorNeutralCardBackgroundPressed: "#C8C8C8",
  colorNeutralCardBackgroundSelected: "#BEBEBE",
  colorNeutralCardBackgroundDisabled: "#F3F2F1",
  colorNeutralStrokeAccessible: "#0078D4",
  colorNeutralStrokeAccessibleHover: "#005A9E",
  colorNeutralStrokeAccessiblePressed: "#004578",
  colorNeutralStrokeAccessibleSelected: "#002847",
  colorNeutralStroke1Hover: "#E1E1E1",
  colorNeutralStroke1Selected: "#C8C8C8",
  colorNeutralStroke2Selected: "#BEBEBE",
  colorNeutralStrokeSubtle: "#D9D9D9",
  colorNeutralStrokeOnBrand: "#FFFFFF",
  colorNeutralStrokeOnBrand2: "#E1E1E1",
  colorNeutralStrokeOnBrand2Hover: "#C8C8C8",
  colorNeutralStrokeOnBrand2Pressed: "#A6A6A6",
  colorNeutralStrokeOnBrand2Selected: "#737373",
  colorBrandStroke1: "#004578",
  colorBrandStroke2: "#005A9E",
  colorBrandStroke2Hover: "#0078D4",
  colorBrandStroke2Pressed: "#2899f5",
  colorBrandStroke2Contrast: "#FFFFFF",
  colorCompoundBrandStroke: "#004578",
  colorCompoundBrandStrokeHover: "#005A9E",
  colorCompoundBrandStrokePressed: "#0078D4",
  colorNeutralStrokeDisabled: "#F3F2F1",
  colorNeutralStrokeInvertedDisabled: "#D9D9D9",
  colorTransparentStroke: "#00000000",
  colorTransparentStrokeInteractive: "#F3F2F1",
  colorTransparentStrokeDisabled: "#E1E1E1",
  colorNeutralStrokeAlpha: "#C8C8C8",
  colorNeutralStrokeAlpha2: "#A6A6A6",
  colorStrokeFocus1: "#0078D4",
  colorStrokeFocus2: "#004578",
  colorNeutralShadowAmbient: "#00000040",
  colorNeutralShadowKey: "#00000070",
  colorNeutralShadowAmbientLighter: "#00000020",
  colorNeutralShadowKeyLighter: "#00000050",
  colorNeutralShadowAmbientDarker: "#00000080",
  colorNeutralShadowKeyDarker: "#000000B0",
  colorBrandShadowAmbient: "#00457840",
  colorBrandShadowKey: "#00457870",
};
//must add tokens also for the borderRadiusMedium so border size?

export function convertColor(color: string): string {
  if (color.startsWith("${tokens.") && color.endsWith("}")) {
    const tokenName = color.slice(9, -1); // Remove '${tokens.' and '}'
    return colorTokens[tokenName] || color;
  } else if (color.endsWith("Accent")) {
    return colorTokens[color];
  } else if (color.startsWith("var")) {
    const tokenName = color.slice(6, -1); // Remove 'var(--' and ')'
    return colorTokens[tokenName];
  }
  return color;
}

export function escapeXml(unsafe: string): string {
  return unsafe.replace(/[<>&'"]/g, function (c) {
    switch (c) {
      case "<":
        return "&lt;";
      case ">":
        return "&gt;";
      case "&":
        return "&amp;";
      case "'":
        return "&apos;";
      case '"':
        return "&quot;";
    }
    return c;
  });
}
