# Use an official Python runtime as a parent image
FROM continuumio/miniforge3

# Set environment variables
ENV PATH /opt/conda/bin:$PATH
ENV SHELL /bin/bash

# Set the working directory
WORKDIR /workspace

# Create the Conda environment with Python 3.11.8
RUN conda create -n pyenv python=3.11.8 -y \
    && echo "conda activate pyenv" >> ~/.bashrc

# Activate the Conda environment and install Prompt flow SDK
RUN /bin/bash -c "source ~/.bashrc \
    && conda activate pyenv \
    && pip install promptflow --upgrade"

# Install Apple's MLX Framework
RUN /bin/bash -c "source ~/.bashrc \
    && conda activate pyenv \
    && pip install mlx-lm"

# Copy the requirements.txt to the container
COPY requirements.txt .

# Install other Python libraries from requirements.txt
RUN /bin/bash -c "source ~/.bashrc \
    && conda activate pyenv \
    && pip install -r requirements.txt"

# Install NVM and Node.js 18.20.0
RUN apt-get update && apt-get install -y curl \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash \
    && export NVM_DIR="$HOME/.nvm" \
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
    && /bin/bash -c "source ~/.bashrc \
    && conda activate pyenv \
    && nvm install 18.20.0 \
    && nvm use 18.20.0"

# Install Visual Studio Code development support tools
RUN /bin/bash -c "source ~/.bashrc \
    && conda activate pyenv \
    && npm install --global yo generator-code"

# Expose ports if needed (example: 8888 for Jupyter)
EXPOSE 8888

# Default command
CMD ["/bin/bash"]
